---
- hosts: all
  become: true
  task:
#  - name: update distribution
#    apt:
#      apt-get update: yes
  - name: install git
    apt:
      name:
        - git
        - nodejs
        - npm
      apt-get update: yes