---
- hosts: all
  become: true
  tasks:
    - name: docker install package
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common


    - name: ajout de la cle gpg
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/debian stretch stable
        state: present

    - name: installer docker
      raw: name={{ item }} state=installed
      with_items:
        - python3
        - python3-pip
        - docker-ce
        - docker-ce-cli
        - containerd.io
      tags:
        - packages

    - name: start docker service
      service:
        name: docker start
        state: started
        enabled: yes