---
- hosts: all
  become: true
  tasks:
    - name: docker install package
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common


    - name: ajout de la cle gpg
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/debian stretch stable

    - name: install docker composents
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes

    - name: start docker service
      service:
        name: docker start
        state: started
        enabled: yes