---
- hosts: all
  become: true
  tasks:
    - name: installer docker
      raw: name={{ item }} state=installed
      with_items:
        - python3
        - python3-pip
        - docker-ce
        - docker-ce-cli
        - containerd.io
      tags:
        - packages
    - name: copier les sources des projets
      copy: 
        src: Exo2/web_app/
        dest: /web_app
    - name: droit pour le dossier
      file: 
        path: /web_app
        node: '0755'
        state: directory
        recurse: true
    - name: generer l'images result
      community.docker.docker_image:
        build:
          path: /web_app/result
        name: result-app
        tag: v1
        push: yes
        source: build
    - name: generer l'images vote
      community.docker.docker_image:
        build:
          path: /web_app/vote
        name: voting-app
        tag: v1
        push: yes
        source: build
    - name: generer l'images worker
      community.docker.docker_image:
        build:
          path: /web_app/worker
        name: worker
        tag: v1
        push: yes
        source: build

    - name: rm folder
      commands: rm -rf /web_app 
