---
- hosts: all
  become: true
  tasks:
    - name: installa dipendenze
      apt:
        name: "{{item}}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: aggiungi chiave GPG
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: aggiungi repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bionic stable
        state: present
    - name: installa docker
      apt:
        name: "{{item}}"
        state: latest
        loop:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
    - name: assicurati che docker sia attivo
      service:
        name: docker
        state: started
        enabled: yes